apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw3.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hw3.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hw3.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "hw3.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_url
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db_username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db_password